apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.metadata.name | default .Release.Name}}-service"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
  labels:
    app: {{ .Release.Name }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      

  selector:
    app: {{ .Release.Name }}

